// Seed data for /admin moderation queue.
// Mix of Open/Hidden/Resolved across all content types, citizen+rep reporters.

window.AD_REPORTS = [
  {
    id: 14207,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88341',
    targetHost: 'Byron Donalds · post #2210',
    preview: "This is just more partisan garbage from a career politician who clearly doesn't care about anyone in FL-19. He should be ashamed.",
    author: 'Maria H. (citizen)',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Personal attack on a public official, repeat behavior on this account.',
    reporter: 'Office of B. Donalds',
    reporterKind: 'rep',
    autoFlag: false,
    when: '12m ago',
    whenAbs: 'Today 10:14 AM',
    status: 'open',
  },
  {
    id: 14206,
    type: 'post',
    typeLabel: 'Rep post',
    targetId: 'post#2208',
    targetHost: 'Rep · J. Rivera-Cantú',
    preview: 'Just confirmed — every dollar of the new infrastructure bill is going directly into private contractor pockets. Sources next week.',
    author: 'Rep · J. Rivera-Cantú',
    authorRole: 'rep',
    reason: 'Misinformation',
    reasonKey: 'misinfo',
    reasonDetail: 'Claim is unverifiable; no source attached. Three other citizens reported.',
    reporter: 'David Okafor',
    reporterKind: 'citizen',
    autoFlag: true,
    when: '47m ago',
    whenAbs: 'Today 9:39 AM',
    status: 'open',
  },
  {
    id: 14205,
    type: 'pollcomment',
    typeLabel: 'Comment on poll',
    targetId: 'pollcomment#3104',
    targetHost: 'Poll · "Support SB-440?"',
    preview: 'Anyone voting yes on this is genuinely brain-damaged. Look around at what these people have done to our state.',
    author: 'Travis K. (citizen)',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Insulting other voters; second report this week.',
    reporter: 'Rep · M. Alvarez',
    reporterKind: 'rep',
    autoFlag: false,
    when: '1h ago',
    whenAbs: 'Today 9:08 AM',
    status: 'hidden',
  },
  {
    id: 14204,
    type: 'poll',
    typeLabel: 'Citizen poll',
    targetId: 'poll#4471',
    targetHost: 'Citizen poll · "Should the mayor resign?"',
    preview: 'Should the mayor resign? Click to claim your free $500 gift card while you decide — limited time link in bio →',
    author: 'free_offer_bot',
    authorRole: 'citizen',
    reason: 'Spam',
    reasonKey: 'spam',
    reasonDetail: 'Affiliate link, account created 2h ago, no other activity.',
    reporter: 'Auto-detect',
    reporterKind: 'system',
    autoFlag: true,
    when: '2h ago',
    whenAbs: 'Today 8:11 AM',
    status: 'open',
  },
  {
    id: 14203,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88298',
    targetHost: 'Byron Donalds · post #2204',
    preview: 'You all sound exactly like the people you claim to hate. Maybe touch grass.',
    author: 'pinetree_42 (citizen)',
    authorRole: 'citizen',
    reason: 'Off-topic',
    reasonKey: 'offtopic',
    reasonDetail: '',
    reporter: 'Linda S.',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '3h ago',
    whenAbs: 'Today 7:02 AM',
    status: 'open',
  },
  {
    id: 14201,
    type: 'post',
    typeLabel: 'Rep post',
    targetId: 'post#2199',
    targetHost: 'Rep · K. Whitfield',
    preview: 'The water rates in Lee County are illegal. I have proof and will be filing suit Monday. Names attached.',
    author: 'Rep · K. Whitfield',
    authorRole: 'rep',
    reason: 'Misinformation',
    reasonKey: 'misinfo',
    reasonDetail: 'Names of private individuals attached without consent; cease-and-desist on file from county counsel.',
    reporter: 'Lee County Counsel',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '6h ago',
    whenAbs: 'Today 4:23 AM',
    status: 'hidden',
  },
  {
    id: 14199,
    type: 'comment',
    typeLabel: 'Comment on post',
    targetId: 'comment#88012',
    targetHost: 'Rep · A. Patel · post #2188',
    preview: 'great post, totally agree we need to do something about this',
    author: 'thomasf',
    authorRole: 'citizen',
    reason: 'Harassment',
    reasonKey: 'harass',
    reasonDetail: 'Reporter retracted: "Sorry — misclick."',
    reporter: 'martin_p',
    reporterKind: 'citizen',
    autoFlag: false,
    when: '1d ago',
    whenAbs: 'Yesterday',
    status: 'resolved',
    resolution: 'Dismissed',
  },
  {
    id: 14196,
    type: 'pollcomment',
    typeLabel: 'Comment on poll',
    targetId: 'pollcomment#3088',
    targetHost: 'Poll · "Beach restoration funds"',
    preview: 'Buy followers cheap! Real US accounts → linkinbio.example',
    author: 'engage_pro_99',
    authorRole: 'citizen',
    reason: 'Spam',
    reasonKey: 'spam',
    reasonDetail: '',
    reporter: 'Auto-detect',
    reporterKind: 'system',
    autoFlag: true,
    when: '2d ago',
    whenAbs: 'Mon, May 13',
    status: 'resolved',
    resolution: 'Author suspended',
  },
];

window.AD_KPIS = {
  open: 5,
  hidden: 12,
  resolvedWeek: 47,
};

// =========================================================
// Seed data for /admin/appeals — appeals filed against
// moderation actions (hidden content OR account suspension).
// =========================================================
window.AD_APPEALS = [
  {
    id: 8821,
    status: 'pending',
    type: 'content',
    targetType: 'comment',
    targetTypeLabel: 'Comment on post',
    targetId: 'comment#88341',
    targetHost: 'Byron Donalds · post #2210',
    targetPreview: "This is just more partisan garbage from a career politician who clearly doesn't care about anyone in FL-19. He should be ashamed.",
    moderationAction: 'Hidden by jeff@example.com',
    moderationReason: 'Harassment',
    moderationAt: 'Today 10:24 AM',
    appellantName: 'Maria H.',
    appellantInitials: 'MH',
    appellantKind: 'citizen',
    appellantEmail: 'maria.h@example.com',
    rationale: "I wasn't attacking him personally — I was criticizing the policy. This is a public official taking a public position and citizens have to be able to push back on that. Reading my comment again it could've been more measured, but it's not harassment.",
    filedAt: '32m ago',
    filedAtAbs: 'Today 10:56 AM',
  },
  {
    id: 8820,
    status: 'pending',
    type: 'suspension',
    targetType: 'account',
    targetTypeLabel: 'Account suspension',
    targetId: 'user#4421',
    targetHost: 'travis.k@example.com',
    moderationAction: 'Suspended by jeff@example.com',
    moderationReason: 'Insulting other voters; second report this week.',
    moderationAt: 'Yesterday 6:14 PM',
    appellantName: 'Travis K.',
    appellantInitials: 'TK',
    appellantKind: 'citizen',
    appellantEmail: 'travis.k@example.com',
    rationale: "I called people brain-damaged, fair enough, that was out of line. But a full suspension is way too far — I've been on CivicView for two years and this is my first thing. A warning would've done the same job. I'll keep it cleaner.",
    filedAt: '4h ago',
    filedAtAbs: 'Today 7:08 AM',
  },
  {
    id: 8819,
    status: 'pending',
    type: 'content',
    targetType: 'post',
    targetTypeLabel: 'Rep post',
    targetId: 'post#2199',
    targetHost: 'Rep · K. Whitfield',
    targetPreview: 'The water rates in Lee County are illegal. I have proof and will be filing suit Monday. Names attached.',
    moderationAction: 'Hidden by jeff@example.com',
    moderationReason: 'Misinformation — names of private individuals attached without consent; cease-and-desist on file from county counsel.',
    moderationAt: 'Today 4:48 AM',
    appellantName: 'Rep · K. Whitfield',
    appellantInitials: 'KW',
    appellantKind: 'rep',
    appellantEmail: 'office@whitfield.house.gov',
    rationale: "These names are already in the public record — they appeared in the county's own publicly-posted contractor list. I redacted any home addresses or personal contact info. The C&D doesn't have legal force here; the office is welcome to clarify what's actually private.",
    filedAt: '5h ago',
    filedAtAbs: 'Today 6:02 AM',
  },
  {
    id: 8817,
    status: 'granted',
    type: 'content',
    targetType: 'comment',
    targetTypeLabel: 'Comment on post',
    targetId: 'comment#88012',
    targetHost: 'Rep · A. Patel · post #2188',
    targetPreview: 'great post, totally agree we need to do something about this',
    moderationAction: 'Hidden by jeff@example.com',
    moderationReason: 'Harassment (reporter retracted: misclick).',
    moderationAt: 'Yesterday 1:14 PM',
    appellantName: 'thomas_f',
    appellantInitials: 'TF',
    appellantKind: 'citizen',
    appellantEmail: 'thomas.f@example.com',
    rationale: "I didn't do anything? The person who reported me said it was a misclick.",
    filedAt: '1d ago',
    filedAtAbs: 'Yesterday',
    resolution: {
      decision: 'granted',
      by: 'jeff@example.com',
      at: '14m ago',
      note: 'Reporter confirmed misclick — content reinstated.',
    },
  },
  {
    id: 8815,
    status: 'denied',
    type: 'suspension',
    targetType: 'account',
    targetTypeLabel: 'Account suspension',
    targetId: 'user#1027',
    targetHost: 'free_offer_bot@example.com',
    moderationAction: 'Suspended by jeff@example.com',
    moderationReason: 'Spam — affiliate links across multiple polls; account created 2h before first action.',
    moderationAt: 'Mon, May 13',
    appellantName: 'free_offer_bot',
    appellantInitials: 'FO',
    appellantKind: 'citizen',
    appellantEmail: 'free_offer_bot@example.com',
    rationale: 'real account please unsuspend, was sharing helpful resource for community link in bio.',
    filedAt: '2d ago',
    filedAtAbs: 'Mon, May 13',
    resolution: {
      decision: 'denied',
      by: 'jeff@example.com',
      at: '2d ago',
      note: 'Account flagged by auto-detect with 4 prior signals; rationale is itself promotional. Denied.',
    },
  },
];

window.AD_APPEALS_KPIS = {
  open: 3,
  grantedWeek: 4,
  deniedWeek: 6,
};

// =========================================================
// Seed data for /admin/users — suspended accounts
// =========================================================
window.AD_SUSPENDED = [
  {
    id: 'user#4421',
    name: 'Travis K.',
    initials: 'TK',
    kind: 'citizen',
    email: 'travis.k@example.com',
    suspendedAt: 'Yesterday 6:14 PM',
    suspendedRel: '18h ago',
    suspendedBy: 'jeff@example.com',
    reason: 'Insulting other voters across multiple poll comment threads. Second report this week.',
    reasonShort: 'Insulting other voters; 2nd report this week.',
    reportCount: 4,
    hasAppeal: true,
  },
  {
    id: 'user#1027',
    name: 'free_offer_bot',
    initials: 'FO',
    kind: 'citizen',
    email: 'free_offer_bot@example.com',
    suspendedAt: 'Mon, May 13 · 9:08 AM',
    suspendedRel: '2d ago',
    suspendedBy: 'jeff@example.com',
    reason: 'Spam — affiliate links across multiple polls; account created 2h before first action. Auto-detect flagged.',
    reasonShort: 'Spam — affiliate links across polls.',
    reportCount: 9,
    hasAppeal: false,
  },
  {
    id: 'user#3308',
    name: 'engage_pro_99',
    initials: 'EP',
    kind: 'citizen',
    email: 'engage_pro_99@example.com',
    suspendedAt: 'Mon, May 13 · 8:11 AM',
    suspendedRel: '2d ago',
    suspendedBy: 'jeff@example.com',
    reason: '"Buy followers" promo posts on poll comment threads. Auto-detect surfaced 3 instances in 6 minutes.',
    reasonShort: 'Follower-farm promo on poll comments.',
    reportCount: 6,
    hasAppeal: false,
  },
  {
    id: 'rep#88',
    name: 'Rep · D. Marsh (FL-22, candidate)',
    initials: 'DM',
    kind: 'rep',
    email: 'marsh.candidate@example.com',
    suspendedAt: 'Fri, May 9 · 2:47 PM',
    suspendedRel: '6d ago',
    suspendedBy: 'jeff@example.com',
    reason: "Repeated misinformation about a sitting rep's voting record; refused to attach sources after two warnings.",
    reasonShort: 'Repeated misinformation re: voting record.',
    reportCount: 12,
    hasAppeal: false,
  },
  {
    id: 'user#2210',
    name: 'pinetree_42',
    initials: 'P4',
    kind: 'citizen',
    email: 'pinetree42@example.com',
    suspendedAt: 'Thu, May 8 · 11:33 AM',
    suspendedRel: '7d ago',
    suspendedBy: 'jeff@example.com',
    reason: 'Harassment of three different citizens across two rep pages. Pattern of escalation.',
    reasonShort: 'Harassment across two rep pages.',
    reportCount: 7,
    hasAppeal: false,
  },
];

window.AD_SUSPENDED_KPIS = {
  current: 14,
  suspendedWeek: 5,
  unsuspendedWeek: 2,
};
